POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Megumi",
    "number": "1234-87384"
}

###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "number": "1234"
}