POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Megumi",
    "number": "23232323-4545445-434343"
}

###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "number": "1234"
}